config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :monthly_steps
  resources :monthly_goals
  resources :todo_list_tasks do
    member do
      post 'complete_task'
    end
  end
  # config/routes.rb
get 'completed_tasks', to: 'todo_list_tasks#completed_tasks', as: 'completed_tasks'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "todo_list_tasks#index"
end

app/models/monthly_step.rb
class MonthlyStep < ApplicationRecord
  belongs_to :monthly_goals
end

app/controllers/monthly_steps_controller.rb
class MonthlyStepsController < ApplicationController
  before_action :set_monthly_step, only: %i[ show edit update destroy ]

  # GET /monthly_steps or /monthly_steps.json
  def index
    @monthly_steps = MonthlyStep.all
  end

  # GET /monthly_steps/1 or /monthly_steps/1.json
  def show
  end

  # GET /monthly_steps/new
  def new
    @monthly_step = MonthlyStep.new
  end

  # GET /monthly_steps/1/edit
  def edit
  end

  # POST /monthly_steps or /monthly_steps.json
  def create
    @monthly_step = MonthlyStep.new(monthly_step_params)

    respond_to do |format|
      if @monthly_step.save
        format.html { redirect_to monthly_step_url(@monthly_step), notice: "Monthly step was successfully created." }
        format.json { render :show, status: :created, location: @monthly_step }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @monthly_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monthly_steps/1 or /monthly_steps/1.json
  def update
    respond_to do |format|
      if @monthly_step.update(monthly_step_params)
        format.html { redirect_to monthly_step_url(@monthly_step), notice: "Monthly step was successfully updated." }
        format.json { render :show, status: :ok, location: @monthly_step }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @monthly_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monthly_steps/1 or /monthly_steps/1.json
  def destroy
    @monthly_step.destroy

    respond_to do |format|
      format.html { redirect_to monthly_steps_url, notice: "Monthly step was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monthly_step
      @monthly_step = MonthlyStep.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def monthly_step_params
      params.require(:monthly_step).permit(:title, :description, :due_date, :monthly_goals_id)
    end
end

app/views/monthly_steps/_form.html.erb
<%= simple_form_for(@monthly_step) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :due_date %>
    <%= f.association :monthly_goals %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/monthly_steps/_monthly_step.html.erb
<div id="<%= dom_id monthly_step %>">
  <p>
    <strong>Title:</strong>
    <%= monthly_step.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= monthly_step.description %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= monthly_step.due_date %>
  </p>

  <p>
    <strong>Monthly goals:</strong>
    <%= monthly_step.monthly_goals_id %>
  </p>

</div>

app/views/monthly_steps/edit.html.erb
<h1>Editing monthly step</h1>

<%= render "form", monthly_step: @monthly_step %>

<br>

<div>
  <%= link_to "Show this monthly step", @monthly_step %> |
  <%= link_to "Back to monthly steps", monthly_steps_path %>
</div>

app/views/monthly_steps/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Monthly steps</h1>

<div id="monthly_steps">
  <% @monthly_steps.each do |monthly_step| %>
    <%= render monthly_step %>
    <p>
      <%= link_to "Show this monthly step", monthly_step %>
    </p>
  <% end %>
</div>

<%= link_to "New monthly step", new_monthly_step_path %>

app/views/monthly_steps/new.html.erb
<h1>New monthly step</h1>

<%= render "form", monthly_step: @monthly_step %>

<br>

<div>
  <%= link_to "Back to monthly steps", monthly_steps_path %>
</div>

app/views/monthly_steps/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @monthly_step %>

<div>
  <%= link_to "Edit this monthly step", edit_monthly_step_path(@monthly_step) %> |
  <%= link_to "Back to monthly steps", monthly_steps_path %>

  <%= button_to "Destroy this monthly step", @monthly_step, method: :delete %>
</div>