config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :monthly_steps
  resources :monthly_goals
  resources :todo_list_tasks do
    member do
      post 'complete_task'
    end
  end
  # config/routes.rb
get 'completed_tasks', to: 'todo_list_tasks#completed_tasks', as: 'completed_tasks'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "todo_list_tasks#index"
end

app/models/monthly_goal.rb
class MonthlyGoal < ApplicationRecord
  belongs_to :user
  has_many :monthly_steps
  validates :priority, inclusion: { in: ["Low Priority" , "Medium Priority" , "High Priority"]}
  validates :title, :description, :priority, presence: true
end

app/controllers/monthly_goals_controller.rb
class MonthlyGoalsController < ApplicationController
  before_action :set_monthly_goal, only: %i[ show edit update destroy ]

  # GET /monthly_goals or /monthly_goals.json
  def index
    @monthly_goals = MonthlyGoal.all
    @monthly_goal = MonthlyGoal.new
  end

  # GET /monthly_goals/1 or /monthly_goals/1.json
  def show
  end

  # GET /monthly_goals/new
  def new
    @monthly_goal = MonthlyGoal.new
  end

  # GET /monthly_goals/1/edit
  def edit
  end

  # POST /monthly_goals or /monthly_goals.json
  def create
    @monthly_goal = MonthlyGoal.new(monthly_goal_params)
    @monthly_goal.user = current_user


    respond_to do |format|
      if @monthly_goal.save
        format.html { redirect_to monthly_goal_url(@monthly_goal), notice: "Monthly goal was successfully created." }
        format.json { render :show, status: :created, location: @monthly_goal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @monthly_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monthly_goals/1 or /monthly_goals/1.json
  def update
    respond_to do |format|
      if @monthly_goal.update(monthly_goal_params)
        format.html { redirect_to monthly_goal_url(@monthly_goal), notice: "Monthly goal was successfully updated." }
        format.json { render :show, status: :ok, location: @monthly_goal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @monthly_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monthly_goals/1 or /monthly_goals/1.json
  def destroy
    @monthly_goal.destroy

    respond_to do |format|
      format.html { redirect_to monthly_goals_url, notice: "Monthly goal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monthly_goal
      @monthly_goal = MonthlyGoal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def monthly_goal_params
      params.require(:monthly_goal).permit(:title, :description, :priority)
    end
end

app/views/monthly_goals/_form.html.erb
<%= simple_form_for(@monthly_goal) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

 <div class="beachformmg">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :priority, as: :select, collection: ["Low Priority", "Medium Priority", "High Priority"], label: "Priority", input_html: { class: "priority-select"} %>



  <div class="form-actions">
     <%= f.button :submit, "Create My Monthly Goal", class: "createbuttonmg"%>
  </div>
</div>
<% end %>

app/views/monthly_goals/_monthly_goal.html.erb
<div id="<%= dom_id monthly_goal %>">




<div class="minicard mt-3 mx-2" data-bs-toggle="popover" data-bs-title=" <%= monthly_goal.title %>" data-bs-content="<%= monthly_goal.description%>" data-custom-popover="true" data-bs-placement="top" data-bs-custom-class="custom-popover">
<% if monthly_goal.priority== "Low Priority" %>
<div class="prio-style1"></div>
<% elsif monthly_goal.priority== "Medium Priority"%>
<div class="prio-style2"></div>
<% else %>
<div class="prio-style3"></div>
<% end %>
<p class="ms-4 ">
    <%= monthly_goal.title %><br>
    </p>





 </div>


</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]');
    const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl));

  });
  const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>

<style>
.popover  {
  background: rgba(255, 255, 255, 0.25);
  box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
  backdrop-filter: blur(4px);
  -webkit-backdrop-filter: blur(4px);
  border-radius: 10px;
  border: 1px solid rgba(255, 255, 255, 0.18);
}
.custom-popover{
 --bs-popover-max-width: 600px;
  --bs-popover-border-color: var(--bd-violet-bg);
  --bs-popover-header-bg: var(--bd-violet-bg);
  --bs-popover-header-color: #191919;
  --bs-popover-body-padding-x: 1rem;
  --bs-popover-body-padding-y: .5rem;

}
.minicard:hover{
  transform:scale(1.1);
  cursor:pointer;
}


</style>

app/views/monthly_goals/edit.html.erb
<h1>Editing monthly goal</h1>

<%= render "form", monthly_goal: @monthly_goal %>

<br>

<div>
  <%= link_to "Show this monthly goal", @monthly_goal %> |
  <%= link_to "Back to monthly goals", monthly_goals_path %>
</div>

app/views/monthly_goals/index.html.erb
<p style="color: green"><%= notice %></p>
<h1 >Monthly goals</h1>

<div class="d-flex justify-content-center">
<div class="card1">

  <% @monthly_goals.each do |monthly_goal| %>
    <%= render monthly_goal %>

  <% end %>
   <div class="minicard mt-3 mx-2" id="addmg">
<%= link_to new_monthly_goal_path do %>
  <img src="assets/addmonthlygoal.png" class="addmonthlygoal" width="50px" height="70px" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Tooltip on bottom">
<% end %>
   </div>
</div>
</div>
<script>
const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>

app/views/monthly_goals/new.html.erb
<div class="d-flex justify-content-center">

<h1>New monthly goal</h1>


<%= render "form", monthly_goal: @monthly_goal %>

<br>

<div>
  <%= link_to "Back to monthly goals", monthly_goals_path %>
</div>
</div>

app/views/monthly_goals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @monthly_goal %>

<div>
  <%= link_to "Edit this monthly goal", edit_monthly_goal_path(@monthly_goal) %> |
  <%= link_to "Back to monthly goals", monthly_goals_path %>

  <%= button_to "Destroy this monthly goal", @monthly_goal, method: :delete %>
</div>